name: Docker Image
on:
  release:
    types: [published] 

jobs:
  test:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Setup
        id: prep
        run: |
          ## Normalized image
          repo_name=${GITHUB_REPOSITORY#*/}
          echo "image=${{ github.repository_owner }}/${repo_name#docker-}" >> $GITHUB_OUTPUT
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.prep.outputs.image }}
          tags: |
            type=semver,pattern={{major}}.{{minor}},priority=901
            type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER || github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
